### PR TITLE
Create build-develop.yml

### PR DESCRIPTION
**Pull request by Zageron**
Example simple build. #5

### CODE REVIEW

**Comment by Trumpet63** [comment]
From what I can tell: I think this adds a GitHub Check to every pull request. I'm not sure what checkout@v2 is doing. With how you linked to #5 I assume this accomplishes "Create action which builds Dockerfile and pushes to organization package registry." but I don't fully understand what that means and I don't know how to verify that your commit actually does that. Speaking of - is there any way to make it so that I don't have to see your commit history? How you got to this one working commit isn't really relevant to me the reviewer, nor to someone who is later looking through commits trying to figure out when something broke.

**Comment by Zageron** [comment]
- Yes, I will use squash and merge when accepting this. (See "merge pull request" drop-down.)
- Checkout@v2 is a built in github action which clones the repository into the actions workspace. ([See more about Checkout@v2](https://github.com/actions/checkout))

**Comment by Trumpet63** [comment]
Okay, still trying to get a basic story in my head. This code will let you create a new Docker image each time there's a pull request, and naturally checking out the code is part of this. What does that enable us to do and/or what is that moving towards?

**Comment by Zageron** [comment]
So the primary goal of using the Docker workflow means that you can guarantee that the work that you do is built a single time, and then deployed to the server. You don't need to fiddle with pushing files to the server, configuring things through ssh, or using git to clone your code to the server and running a 'configure and launch' command.

Instead you build and test locally, it builds on github for validation, and then the image is saved and can be automatically rolled out to your servers.

Essentially: Build and test locally, deploy to a test server, validate with flighting or manual testing, roll-out to main servers.

It sounds overkill, but it is incredibly robust and makes for easy scaling if it ever happens. (Once I get the secrets finished, we'll have a deployed site whenever we want with very little effort, and we can save money by destroying the server when we don't need it.)

**Review by Trumpet63 — APPROVED** [review]
Sounds awesome!

**Pull request closed without merging**
